spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
---
fiap:
  payment:
    queue:
      url: ${PAYMENT_QUEUE_URL}
  production:
    #url: http://localhost:8082
    url: ${PRODUCTION_BASE_URL}